# This script is called by the main CMakeLists.txt to convert a binary file (like a font)
# into a C++ header file containing a byte array.

if(NOT ARGC EQUAL 3)
    message(FATAL_ERROR "Usage: font_to_header.cmake <input_file> <output_file> <array_name>")
endif()

set(INPUT_FILE ${ARGV0})
set(OUTPUT_FILE ${ARGV1})
set(ARRAY_NAME ${ARGV2})

# Read the binary file into a hex string
file(READ ${INPUT_FILE} FONT_HEX HEX)
# Use regex to format the hex string into a C-style byte array (e.g., "0xAB,0xCD,...")
string(REGEX REPLACE "([0-9a-fA-F]{2})" "0x\\1," FONT_C_ARRAY "${FONT_HEX}")

# Get the size of the file for the array size variable
file(SIZE ${INPUT_FILE} FONT_SIZE)

# Write the final C++ header file
file(WRITE ${OUTPUT_FILE}
"#pragma once\n"
"// This file is generated by cmake/font_to_header.cmake\n\n"
"#include <cstddef> // for size_t\n\n"
"const unsigned char ${ARRAY_NAME}_data[] = {\n"
"    ${FONT_C_ARRAY}\n"
"};\n"
"const size_t ${ARRAY_NAME}_size = ${FONT_SIZE};\n"
)
